# Generated by Django 4.2.6 on 2023-10-28 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='departmentdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depname', models.CharField(blank=True, max_length=100, null=True)),
                ('depcat', models.CharField(blank=True, max_length=100, null=True)),
                ('depdes', models.CharField(blank=True, max_length=600, null=True)),
                ('depimg', models.ImageField(blank=True, null=True, upload_to='department')),
            ],
        ),
    ]
