# Generated by Django 4.2.6 on 2023-10-29 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_departmentdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='profiledb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(blank=True, max_length=100, null=True)),
                ('uname', models.CharField(max_length=100)),
                ('pmail', models.EmailField(blank=True, max_length=100, null=True)),
                ('pmobile', models.IntegerField(blank=True, max_length=100, null=True)),
                ('paddress', models.CharField(blank=True, max_length=300, null=True)),
                ('pcode', models.IntegerField(blank=True, max_length=100, null=True)),
                ('pstate', models.CharField(blank=True, max_length=100, null=True)),
                ('pimage', models.ImageField(blank=True, null=True, upload_to='profileimg')),
            ],
        ),
    ]
