# Generated by Django 4.2.6 on 2023-11-13 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_profiledb'),
    ]

    operations = [
        migrations.CreateModel(
            name='doctordb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dname', models.CharField(blank=True, max_length=100, null=True)),
                ('dep', models.CharField(blank=True, max_length=100, null=True)),
                ('special', models.CharField(blank=True, max_length=100, null=True)),
                ('dmail', models.EmailField(blank=True, max_length=100, null=True)),
                ('dphone', models.IntegerField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, max_length=100, null=True)),
                ('fee', models.IntegerField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
