# Generated by Django 4.2.6 on 2023-11-19 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_doctordb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctordb',
            name='dep',
        ),
    ]
