# Generated by Django 4.2.6 on 2023-12-04 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_doctordb_profile_doctordb_qualification'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctordb',
            name='doctorid',
            field=models.IntegerField(null=True, blank=True),
            preserve_default=False,
        ),
    ]
