# Generated by Django 4.2.6 on 2023-12-04 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_doctordb_doctorid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctordb',
            name='doctorid',
        ),
    ]
