# Generated by Django 4.2.6 on 2023-12-04 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_doctordb_doctorid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='doctordb',
        ),
    ]
