# Generated by Django 4.2.6 on 2023-12-04 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_doctordb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiledb',
            name='pcode',
        ),
        migrations.AlterField(
            model_name='doctordb',
            name='doctorid',
            field=models.CharField(max_length=50),
        ),
    ]
