# Generated by Django 4.2.6 on 2023-12-04 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_remove_doctordb_doctorid'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctordb',
            name='doctorid',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
