# Generated by Django 4.2.6 on 2023-12-04 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_doctordb_doctorid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctordb',
            name='doctorid',
            field=models.IntegerField(default=3, unique=True),
            preserve_default=False,
        ),
    ]
