# Generated by Django 4.2.6 on 2023-12-04 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_alter_doctordb_doctorid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctordb',
            name='id',
        ),

    ]
