# Generated by Django 4.2.6 on 2023-12-06 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_doctordb_id_alter_doctordb_doctorid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='doctordb',
        ),
    ]
