# Generated by Django 4.2.6 on 2023-12-06 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_doctordb'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctordb',
            name='password',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
