# Generated by Django 4.2.6 on 2023-12-10 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_doctordb_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctordb',
            name='dphone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
