# Generated by Django 5.0 on 2024-01-15 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_alter_doctordb_dphone'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctordb',
            name='Experiance',
            field=models.CharField(blank=True, default='Fresher', max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='doctordb',
            name='Location',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='doctordb',
            name='address',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
