# Generated by Django 5.0 on 2024-01-15 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_doctordb_experiance_doctordb_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctordb',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='profile'),
        ),
    ]
