# Generated by Django 5.0 on 2024-01-15 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_alter_doctordb_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctordb',
            name='profileimage',
            field=models.ImageField(blank=True, null=True, upload_to='profile'),
        ),
        migrations.AlterField(
            model_name='doctordb',
            name='profile',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
