# Generated by Django 5.0 on 2024-01-15 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0024_doctordb_profileimage_alter_doctordb_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctordb',
            name='age',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
