# Generated by Django 5.0 on 2024-01-15 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0025_doctordb_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctordb',
            name='dob',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
