# Generated by Django 5.0 on 2024-01-15 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0026_doctordb_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctordb',
            name='profileimage',
            field=models.ImageField(blank=True, default='Untitled.png', null=True, upload_to='profile'),
        ),
    ]
