# Generated by Django 4.2.6 on 2023-11-23 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='appointmentdb',
        ),
    ]
