# Generated by Django 4.2.6 on 2023-11-23 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('frontend', '0002_delete_appointmentdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='appointmentdb',
            fields=[
                ('bookingid', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(blank=True, max_length=50, null=True)),
                ('lastname', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('department', models.CharField(blank=True, max_length=50, null=True)),
                ('doctor', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateField(blank=True, max_length=50, null=True)),
                ('consultation', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('message', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
