# Generated by Django 4.2.6 on 2023-11-23 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentdb',
            name='age',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appointmentdb',
            name='gender',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
