# Generated by Django 5.0 on 2023-12-27 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_contactdb_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactdb',
            name='status',
        ),
    ]
