# Generated by Django 5.0 on 2023-12-27 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_remove_contactdb_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactdb',
            name='reply',
            field=models.CharField(blank=True, default='NOTREPLIED', max_length=200, null=True),
        ),
    ]
