# Generated by Django 5.0 on 2024-01-12 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0010_userdb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userdb',
        ),
    ]
