# Generated by Django 5.0 on 2024-01-12 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0011_delete_userdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='userdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.IntegerField()),
                ('password', models.CharField(max_length=15)),
                ('address', models.CharField(blank=True, max_length=50)),
                ('bloodgroup', models.CharField(blank=True, max_length=10)),
            ],
        ),
    ]
