# Generated by Django 5.0 on 2024-01-14 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0012_userdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdb',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdb',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdb',
            name='sex',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
