# Generated by Django 5.0 on 2024-01-15 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0015_alter_userdb_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdb',
            name='profile',
            field=models.ImageField(blank=True, default='Untitled.png', upload_to='profile'),
        ),
    ]
