# Generated by Django 5.0 on 2024-01-15 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0016_alter_userdb_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentdb',
            name='userid',
            field=models.IntegerField(null=True),
        ),
    ]
