# Generated by Django 5.0 on 2024-01-15 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0017_appointmentdb_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentdb',
            name='remarks',
            field=models.CharField(default='No Remarks', max_length=200, null=True),
        ),
    ]
