# Generated by Django 4.2.6 on 2023-12-14 10:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('backend', '0021_alter_doctordb_dphone'),
        ('doctorapp', '0002_delete_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punch_in_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('punch_out_time', models.DateTimeField(blank=True, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.doctordb')),
            ],
        ),
    ]
