# Generated by Django 5.0 on 2023-12-25 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorapp', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='applyleavedb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('fromdate', models.DateField(blank=True, max_length=100, null=True)),
                ('todate', models.DateField(blank=True, max_length=100, null=True)),
                ('leave', models.CharField(blank=True, max_length=100, null=True)),
                ('reason', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
