# Generated by Django 5.0 on 2023-12-26 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctorapp', '0004_applyleavedb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='applyleavedb',
        ),
    ]
