# Generated by Django 5.0 on 2023-12-26 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorapp', '0006_applyleavedb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applyleavedb',
            name='status',
        ),
        migrations.AlterField(
            model_name='applyleavedb',
            name='fromdate',
            field=models.DateField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='applyleavedb',
            name='todate',
            field=models.DateField(blank=True, max_length=100, null=True),
        ),
    ]
